### ISSUE TITLE
Wrong scale for magnetometer ?

### ISSUE THREAD

**Issue by lgm42** [simondlevy/MPU9250#2]
Why have you a 10 coefficient in mag scale ?

https://github.com/simondlevy/MPU9250/blob/3fd8a07f0883d88d757e68e43d0c8c23e47b944e/src/MPU9250.cpp#L36

https://github.com/simondlevy/MPU9250/blob/3fd8a07f0883d88d757e68e43d0c8c23e47b944e/src/MPU9250.cpp#L40

**Comment by simondlevy** [comment]
MPU9250 [specs](https://www.invensense.com/products/motion-tracking/9-axis/mpu-9250/) are 0.15 uT per Least Significant Bit.  Since 1uT = 10mG(https://www.google.com/search?q=micro+tesla+to+mlligauss&oq=micro+tesla+to+mlligauss&aqs=chrome..69i57j0l3.4137j1j7&sourceid=chrome&ie=UTF-8), multiply by 10 to get mG.

**Comment by lgm42** [comment]
You're right I missed the Tesla I thought it was direclty mG.
Thanks a lot for your job !
